### ISSUE TITLE
investigate networking issues

### ISSUE THREAD

**Issue by modernNeo** [CSSS/wall_e#123]
Wall_e is having increasing networking issues and I believe a symptom of that may be that it is now [disconnected from the bot_log channel](https://discordapp.com/channels/228761314644852736/478776321808269322/497845256759279627) since the channel has not spit out anything for the past 11 days

`2018-10-05 18:59:18 = WARNING - Error in data transfer`
`Traceback (most recent call last):`
`.  File "/usr/local/lib/python3.5/site-packages/websockets/protocol.py", line 496, in transfer_data`
`.    msg = yield from self.read_message()`
`.  File "/usr/local/lib/python3.5/site-packages/websockets/protocol.py", line 526, in read_message`

**Comment by modernNeo** [comment]
indication of networking issues are apparent in logs 2018_09_19_01_18_24 and 2018_09_29_23_30_41

**Comment by modernNeo** [comment]
https://github.com/CSSS/wall_e/pull/124

**Comment by wnfldchen** [comment]
I want to take a look and see if we can have reconnection ability in our code to handle connection resets, perhaps that would help, and also look at if we're exceeding some kind of api limit which is unlikely

**Comment by wnfldchen** [comment]
Yes my conclusion is that this is entirely not our fault and that connection is reset by discord's servers probably due to their own limitations or issues. Exploring delayed reconnect-after-reset solution

**Comment by modernNeo** [comment]
being closed in favor of the Issue https://github.com/CSSS/wall_e/issues/165
