### ISSUE TITLE
wolfram alpha doesnt seem to be in help.json

### ISSUE THREAD

**Issue by modernNeo** [CSSS/wall_e#131]

**Comment by PaymonJ** [comment]
I had done it in https://github.com/CSSS/wall_e/pull/97/commits/db1af5688a8dbe7dee5d66889d583fbc076c0bab but it seems to be gone - guess I'll add it again.

**Comment by PaymonJ** [comment]
Fixed in https://github.com/CSSS/wall_e/pull/141/commits/b6ee93785e3a1b702843c554c2f9e72174d06634 and created pull request https://github.com/CSSS/wall_e/pull/141.
