### ISSUE TITLE
role with emoji cant be created

### ISSUE THREAD

**Issue by modernNeo** [CSSS/wall_e#18]
`.newrole "HufflePuff :sunglasses: "`
`.iam "HufflePuff :sunglasses: "`
not working

**Comment by PaymonJay** [comment]
<img width="508" alt="capture" src="https://user-images.githubusercontent.com/22732152/42603769-0187f0ac-8524-11e8-8d67-94fc913914de.PNG">

I managed to do it 🤔 guessing it's a formatting issue with your arguments.
