### ISSUE TITLE
Bot doesn't run on #sfucsss

### ISSUE THREAD

**Issue by dleslie** [CSSS/wall_e#185]
I mean, here we are, all long in the tooth and dying of old age on IRC, and you young'ns left us for Discord.

/me yells at clouds

**Comment by eqj** [comment]
I'm also experiencing this issue

**Comment by modernNeo** [comment]
@dleslie and @eqj link me to where in what channel this happens?

**Comment by dleslie** [comment]
... You cannot link to IRC. It has no persistence.

**Comment by modernNeo** [comment]
closing issue its not relevant to the bot
