### ISSUE TITLE
add support to restrict who can vote in polls

### ISSUE THREAD

**Issue by modernNeo** [CSSS/wall_e#31]

**Comment by PaymonJay** [comment]
This wouldn't be possible in Discord. The permission of who can and can't add reactions differs from channel to channel and not message to message.

Closing.

**Comment by dmiiller** [comment]
Closing; Not currently possible in Discord.

**Comment by modernNeo** [comment]
this may actually be achievable. will look into it after refactoring

**Comment by modernNeo** [comment]
played around with this.....the idea I had is pretty glitchy and not pretty so not following through with it but it was interesting experimenting
