### ISSUE TITLE
Refactor .remindme parameters

### ISSUE THREAD

**Issue by PaymonJay** [CSSS/wall_e#33]
Currently the format for the command is `.remindme "in 1 hour" "send the email"`. This is pretty janky and I propose to update the command format to `.remindme 1 hour "send the email"` where the command takes three arguments instead of two: the amount, the unit, and the message.

**Comment by modernNeo** [comment]
making this the function parameter will allow for this
`async def command(ctx, *args):`

**Comment by modernNeo** [comment]
being taken care of with PR https://github.com/CSSS/wall_e/pull/44
specifically https://github.com/CSSS/wall_e/pull/44/files#diff-69f2f4a503b60c41d49cfec81f726506

**Comment by modernNeo** [comment]
branch merged
