### ISSUE TITLE
Upload a screenshot of the bot's permission on csss discord

### ISSUE THREAD

**Issue by modernNeo** [CSSS/wall_e#37]
So that any development environment can emulate the permissions exactly

**Comment by wnfldchen** [comment]
i dont have access to permissions any more lol

**Comment by modernNeo** [comment]
uh, who does? @wnfldchen

**Comment by TitanVJ** [comment]
all screenshots posted in the bot management channel

**Comment by modernNeo** [comment]
@TitanVJ i am not in that channel and that doesnt help people who want to do dev work on the bot but have no interest in being in that channel

**Comment by TitanVJ** [comment]
easier solution: edit the invite link in the readme. change the 0 in the permissions field to 2119564375. this will give the bot a role on joining server with the same perms that it currently has in our discord.

**Comment by modernNeo** [comment]
sounds good

**Comment by modernNeo** [comment]
being taken care of with https://github.com/CSSS/wall_e/pull/38

**Comment by wnfldchen** [comment]
doc, discord rep, and the newly elected minions/mods have the permissions; also the test server now has the same permissions
