### ISSUE TITLE
add useful reference links to README

### ISSUE THREAD

**Issue by modernNeo** [CSSS/wall_e#415]
figure out someplace to add this -> https://gist.github.com/Ash-02014/b6f57065f394b54f43666037ade38d32

**Comment by ashharr** [comment]
hi!
can i work on this issue? please assign it to me

**Comment by modernNeo** [comment]
fixed with https://github.com/CSSS/wall_e/wiki/3.-Working-on-the-Bot/55949acb98fc497198429bfae44064cb28c210a6
