### ISSUE TITLE
Discord Bans Public

### ISSUE THREAD

**Issue by notrastko** [CSSS/wall_e#570]
The Discord bot is leaking all bans in the following file: https://dev.sfucsss.org/wall_e/fixtures/banrecords.json
I've made a simple site to search bans easily as a demonstration: https://notrastko.github.io/csss-ban-search/

**Comment by modernNeo** [comment]
i know. i've taken a security through obscurity approach so far because no one else has worked on the bot besides me 🤷🏿‍♀️
