### ISSUE TITLE
create a command to list all available roles

### ISSUE THREAD

**Issue by modernNeo** [CSSS/wall_e#8]

**Comment by TitanVJ** [comment]
no pls, we have so many roles that it would become a very spammy command.

**Comment by modernNeo** [comment]
Then how are people supposed to know what roles exist to add themselves to it?

**Comment by TitanVJ** [comment]
we never had a command for this before and people were able to figure it out.

**Comment by modernNeo** [comment]
Or perhaps there were people who didn't know the roles but also didn't want to ask?

**Comment by modernNeo** [comment]
And you can always format the output to have pages like Henry's help command.

**Comment by TitanVJ** [comment]
that's pretty complex to do rn. but can always do it yourself and make a pull request.

**Comment by modernNeo** [comment]
or I can just leave this issue here for anyone else who decides to undertake that challenge instead :)

**Comment by modernNeo** [comment]
working on it here https://github.com/CSSS/wall_e/tree/adding_list_roles

**Comment by modernNeo** [comment]
PR created for command https://github.com/CSSS/wall_e/pull/25
