### ISSUE TITLE
Certain Symbols Break Wolfram URL

### ISSUE THREAD

**Issue by PaymonJ** [CSSS/wall_e#98]
More symbols need to be handled like `+` currently is being handled.

**Comment by PaymonJ** [comment]
An example of the link breaking: `.wolfram "integral of [(x-1)/((x-2)^(1/2))]"`

**Comment by PaymonJ** [comment]
Looks like the markdown formatting is being messed up when brackets/parenthesis are involved. Investigating.

**Comment by modernNeo** [comment]
also breaks with `.wolfram 10`

**Comment by modernNeo** [comment]
fair enough.
